typography_spectrum: 0.5307543014641851
color:
  brandColors:
    - '#020200'
    - '#282708'
    - '#616121'
    - '#f1f2ec'
    - '#878846'
  brandStrength: 0.8125
  lightness: 0.19701997726224363
  saturation: 0.6300039291381836
  rhythmicContrast: 0.07654488948173821
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8934786743484437
analytics:
  google: null
  facebook: null
  twitter: null
name: iamalexcohen
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: |
  Beyond
purpose: []
